services:
  kafka:
    image: bitnami/kafka:3.6.0
    container_name: kafka
    restart: always
    env_file:
      - ./env/kafka.env
    networks:
      - kafka-network
  producer:
    build:
      dockerfile: build/Dockerfile.producer
    image: indasto1/producer:1.0
    container_name: producer
    restart: always
    env_file:
      - ./env/producer.env
    networks:
      - kafka-network
    ports:
      - "8080:8080"
  consumer:
    build:
      dockerfile: build/Dockerfile.consumer
    image: indasto1/consumer:1.0
    container_name: consumer
    restart: always
    env_file:
      - ./env/consumer.env
    networks:
      - kafka-network
networks:
  kafka-network:
    driver: bridge
